version: '3.8'
services:
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      PUID: ${USER_ID} # for UserID / default = 1000 / mac = 501
      PGID: ${GROUP_ID} # for GroupID / default = 1000 / mac = 20
      TZ: Europe/Paris
      URL: ${SWAG_DOMAIN}
      SUBDOMAINS: wildcard
      VALIDATION: dns
      DNSPLUGIN: cloudflare
      EMAIL: ${SWAG_EMAIL}
    volumes:
      - ./configs/swag:/config
    ports:
      - 443:443
    restart: unless-stopped
  
  authelia:
    image: authelia/authelia
    container_name: authelia
    environment:
      - TZ=Europe/Paris
    volumes:
      - ./configs/authelia:/config
    restart: unless-stopped

networks:
  swag:
    name: swag
